// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TeamCoding
{
    static class Vsix
    {
        public const string Id = "TeamCoding.George Duckett.307fe055-6f5e-40d7-bb11-13abd012e528";
        public const string Name = "TeamCoding";
        public const string Description = "The Team Coding Visual Studio extension helps discover team members who are working in the same area of a Git repository as you. You can set your own username and user image url via settings (Tools->Options->Team Coding), or let it try and figure them out automatically. Once working it will display user icons at the top of your tabs when other users have the same document open, with a white border when the tab is selected and a grey border when it's edited. It will also display text in CodeLens (disable in CodeLens settings) indicating whether someone is currently working on a class/member based on where their caret (text cursor) is as well as showing a coloured caret where they are working for C# and visual basic code.";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "George Duckett";
        public const string Tags = "Collaboration, Teams, Source Control, Git, Pair Programming, Code Review";
    }
}