// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TeamCoding
{
    static class Vsix
    {
        public const string Id = "TeamCoding.George Duckett.307fe055-6f5e-40d7-bb11-13abd012e528";
        public const string Name = "TeamCoding";
        public const string Description = "The Team Coding Visual Studio extension helps discover team members who are working in the same area of a source controlled solution as you. It displays icons on tabs, text in CodeLens is as well as showing a coloured caret where they are working for C# and visual basic code.";
        public const string Language = "en-US";
        public const string Version = "0.2.0";
        public const string Author = "George Duckett";
        public const string Tags = "Collaboration, Teams, Source Control, Git, Pair Programming, Code Review";
    }
}
